/**
 * CommitDialog
 *
 * Shows a diff-style preview of the AI-optimised code, lets the user:
 *  - choose the target branch
 *  - write a commit message
 *  - optionally post an AI-review summary as a PR comment
 *  - push the file back to GitHub via the backend
 */
import { useState, useEffect, useCallback } from "react"
import { motion } from "framer-motion"
import {
  GitCommitHorizontal, GitBranch, Loader2,
  Check, AlertCircle, MessageSquare, ChevronDown,
} from "lucide-react"
import {
  Dialog, DialogContent, DialogHeader,
  DialogTitle, DialogDescription,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import {
  ghGetFile, ghListBranches, ghCommitFile,
  ghListPRs, ghCommentOnPR,
  type GHBranch, type GHPullRequest,
} from "@/services/api"
import type { ReviewResult } from "@/types/review"
import { cn } from "@/lib/utils"

export interface CommitTarget {
  owner: string
  repo: string
  path: string        // file path inside the repo
  defaultBranch: string
}

interface CommitDialogProps {
  open: boolean
  onClose: () => void
  optimizedCode: string
  reviewResult: ReviewResult | null
  target: CommitTarget | null    // null if no file loaded from GitHub
}

type Stage = "idle" | "loading" | "success" | "error"

function buildReviewComment(result: ReviewResult, path: string): string {
  const scoreEmoji = result.score >= 8 ? "🟢" : result.score >= 5 ? "🟡" : "🔴"
  const lines = [
    `## 🤖 CodeSage AI Review — \`${path}\``,
    "",
    `**Score:** ${scoreEmoji} ${result.score}/10`,
    "",
    `**Summary:** ${result.summary}`,
    "",
  ]
  if (result.bugs.length) {
    lines.push("### 🐛 Bugs")
    result.bugs.forEach((b) => lines.push(`- **${b.title}** (${b.severity}): ${b.description}`))
    lines.push("")
  }
  if (result.security.length) {
    lines.push("### 🔒 Security")
    result.security.forEach((s) => lines.push(`- **${s.title}** (${s.severity}): ${s.description}`))
    lines.push("")
  }
  if (result.performance.length) {
    lines.push("### ⚡ Performance")
    result.performance.forEach((p) => lines.push(`- **${p.title}**: ${p.description}`))
    lines.push("")
  }
  lines.push(`**Time complexity:** ${result.timeComplexity}`)
  lines.push(`**Space complexity:** ${result.spaceComplexity}`)
  lines.push("")
  lines.push("---")
  lines.push("*Generated by [CodeSage AI](https://github.com) — powered by Grok*")
  return lines.join("\n")
}

export function CommitDialog({
  open, onClose, optimizedCode, reviewResult, target,
}: CommitDialogProps) {
  const [branches,       setBranches]       = useState<GHBranch[]>([])
  const [selectedBranch, setSelectedBranch] = useState("")
  const [branchOpen,     setBranchOpen]     = useState(false)
  const [commitMessage,  setCommitMessage]  = useState("")
  const [currentSha,     setCurrentSha]     = useState<string | undefined>(undefined)
  const [prs,            setPRs]            = useState<GHPullRequest[]>([])
  const [selectedPR,     setSelectedPR]     = useState<number | null>(null)
  const [postComment,    setPostComment]     = useState(false)

  const [loadStage,   setLoadStage]   = useState<Stage>("idle")
  const [commitStage, setCommitStage] = useState<Stage>("idle")
  const [errorMsg,    setErrorMsg]    = useState("")

  // Reload metadata when dialog opens with a target
  const load = useCallback(async () => {
    if (!target) return
    setLoadStage("loading")
    try {
      const [branchData, fileData, prData] = await Promise.all([
        ghListBranches(target.owner, target.repo),
        ghGetFile(target.owner, target.repo, target.path).catch(() => null),
        ghListPRs(target.owner, target.repo).catch(() => []),
      ])
      setBranches(branchData)
      setSelectedBranch(target.defaultBranch)
      setCurrentSha(fileData?.sha)
      setPRs(prData)
      setLoadStage("idle")
    } catch (e) {
      setLoadStage("error")
      setErrorMsg(e instanceof Error ? e.message : "Failed to load repo info")
    }
  }, [target])

  useEffect(() => {
    if (open && target) {
      setCommitStage("idle")
      setCommitMessage(`chore: apply CodeSage AI optimizations to ${target.path}`)
      setPostComment(false)
      setSelectedPR(null)
      load()
    }
  }, [open, target, load])

  const handleCommit = async () => {
    if (!target || !commitMessage.trim()) return
    setCommitStage("loading")
    setErrorMsg("")
    try {
      await ghCommitFile({
        owner:   target.owner,
        repo:    target.repo,
        path:    target.path,
        message: commitMessage.trim(),
        content: optimizedCode,
        sha:     currentSha,
        branch:  selectedBranch,
      })

      // Optionally post PR comment
      if (postComment && selectedPR && reviewResult) {
        const body = buildReviewComment(reviewResult, target.path)
        await ghCommentOnPR({
          owner:      target.owner,
          repo:       target.repo,
          pullNumber: selectedPR,
          body,
        })
      }

      setCommitStage("success")
    } catch (e) {
      setCommitStage("error")
      setErrorMsg(e instanceof Error ? e.message : "Commit failed")
    }
  }

  const handleClose = () => {
    if (commitStage === "loading") return
    setCommitStage("idle")
    setLoadStage("idle")
    setErrorMsg("")
    onClose()
  }

  // ── no target (code was typed, not loaded from GitHub) ───────────────────────
  if (!target) {
    return (
      <Dialog open={open} onOpenChange={handleClose}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <GitCommitHorizontal className="size-4" />
              Push to GitHub
            </DialogTitle>
            <DialogDescription>
              Load a file from your GitHub repository first — use the Repos browser in the toolbar.
            </DialogDescription>
          </DialogHeader>
          <div className="py-6 text-center">
            <AlertCircle className="size-10 mx-auto text-muted-foreground mb-3" />
            <p className="text-sm text-muted-foreground">
              No GitHub file is currently loaded. Browse your repos and open a file to enable push.
            </p>
          </div>
          <Button variant="outline" className="w-full" onClick={handleClose}>Close</Button>
        </DialogContent>
      </Dialog>
    )
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <GitCommitHorizontal className="size-4 text-primary" />
            Push Optimized Code to GitHub
          </DialogTitle>
          <DialogDescription>
            Commit AI-improved code to{" "}
            <span className="font-mono text-xs text-foreground">
              {target.owner}/{target.repo}/{target.path}
            </span>
          </DialogDescription>
        </DialogHeader>

        {/* Success state */}
        {commitStage === "success" ? (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="py-8 text-center space-y-3"
          >
            <div className="size-14 rounded-full bg-green-500/10 border border-green-500/20 flex items-center justify-center mx-auto">
              <Check className="size-7 text-green-500" />
            </div>
            <h3 className="font-semibold">Commit pushed successfully!</h3>
            <p className="text-sm text-muted-foreground">
              <a
                href={`https://github.com/${target.owner}/${target.repo}/blob/${selectedBranch}/${target.path}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline"
              >
                View file on GitHub ↗
              </a>
            </p>
            <Button className="mt-2" onClick={handleClose}>Done</Button>
          </motion.div>
        ) : (
          <div className="space-y-4 py-1">

            {/* Code preview */}
            <div className="rounded-lg border border-border bg-muted/40 overflow-hidden">
              <div className="flex items-center justify-between px-3 py-2 border-b border-border bg-muted/60">
                <span className="text-xs font-mono text-muted-foreground truncate">{target.path}</span>
                <Badge variant="secondary" className="text-xs shrink-0 ml-2">optimized</Badge>
              </div>
              <ScrollArea className="h-32">
                <pre className="p-3 text-xs font-mono text-foreground/80 whitespace-pre leading-relaxed">
                  {optimizedCode.slice(0, 600)}{optimizedCode.length > 600 ? "\n…" : ""}
                </pre>
              </ScrollArea>
            </div>

            {/* Branch selector */}
            <div className="space-y-1.5">
              <Label className="text-xs">Target branch</Label>
              {loadStage === "loading" ? (
                <Skeleton className="h-9 w-full" />
              ) : (
                <div className="relative">
                  <button
                    onClick={() => setBranchOpen((v) => !v)}
                    className={cn(
                      "w-full flex items-center justify-between gap-2 rounded-md border border-input bg-background",
                      "px-3 h-9 text-sm hover:bg-muted/60 transition-colors"
                    )}
                  >
                    <span className="flex items-center gap-2 truncate">
                      <GitBranch className="size-3.5 text-muted-foreground shrink-0" />
                      {selectedBranch || "Select branch"}
                    </span>
                    <ChevronDown className="size-3.5 text-muted-foreground shrink-0" />
                  </button>
                  {branchOpen && (
                    <div className="absolute z-50 mt-1 w-full rounded-md border border-border bg-popover shadow-lg">
                      <ScrollArea className="max-h-44">
                        {branches.map((b) => (
                          <button
                            key={b.name}
                            onClick={() => { setSelectedBranch(b.name); setBranchOpen(false) }}
                            className={cn(
                              "w-full flex items-center gap-2 px-3 py-2 text-sm hover:bg-muted/60 transition-colors",
                              b.name === selectedBranch && "text-primary font-medium"
                            )}
                          >
                            <GitBranch className="size-3 text-muted-foreground" />
                            {b.name}
                            {b.name === target.defaultBranch && (
                              <Badge variant="outline" className="text-xs ml-auto px-1 py-0">default</Badge>
                            )}
                          </button>
                        ))}
                      </ScrollArea>
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Commit message */}
            <div className="space-y-1.5">
              <Label className="text-xs">Commit message</Label>
              <Input
                value={commitMessage}
                onChange={(e) => setCommitMessage(e.target.value)}
                placeholder="chore: apply AI optimizations"
                className="text-sm h-9"
              />
            </div>

            {/* PR comment toggle */}
            {prs.length > 0 && reviewResult && (
              <>
                <Separator />
                <div className="space-y-2">
                  <button
                    onClick={() => setPostComment((v) => !v)}
                    className="flex items-center gap-2 text-sm font-medium w-full"
                  >
                    <MessageSquare className="size-3.5 text-muted-foreground" />
                    Post AI review as PR comment
                    <div className={cn(
                      "ml-auto size-5 rounded border flex items-center justify-center transition-colors",
                      postComment ? "bg-primary border-primary" : "border-input bg-background"
                    )}>
                      {postComment && <Check className="size-3 text-primary-foreground" />}
                    </div>
                  </button>
                  {postComment && (
                    <div className="pl-5 space-y-1.5">
                      <Label className="text-xs">Select pull request</Label>
                      <ScrollArea className="max-h-28 border border-border rounded-md">
                        {prs.map((pr) => (
                          <button
                            key={pr.number}
                            onClick={() => setSelectedPR(pr.number === selectedPR ? null : pr.number)}
                            className={cn(
                              "w-full flex items-start gap-2 px-3 py-2 text-xs hover:bg-muted/60 transition-colors",
                              selectedPR === pr.number && "bg-primary/5 text-primary"
                            )}
                          >
                            <span className="font-mono text-muted-foreground shrink-0">#{pr.number}</span>
                            <span className="flex-1 text-left truncate">{pr.title}</span>
                            <span className="shrink-0 text-muted-foreground">{pr.head.ref}</span>
                          </button>
                        ))}
                      </ScrollArea>
                    </div>
                  )}
                </div>
              </>
            )}

            {/* Error */}
            {(commitStage === "error" || loadStage === "error") && (
              <div className="flex items-start gap-2 text-destructive bg-destructive/10 border border-destructive/20 rounded-md px-3 py-2">
                <AlertCircle className="size-3.5 shrink-0 mt-0.5" />
                <p className="text-xs">{errorMsg}</p>
              </div>
            )}

            {/* Actions */}
            <div className="flex gap-2 pt-1">
              <Button variant="outline" className="flex-1" onClick={handleClose} disabled={commitStage === "loading"}>
                Cancel
              </Button>
              <Button
                className="flex-1 gap-2 bg-gradient-to-r from-brand-blue to-brand-violet text-white border-0 hover:opacity-90"
                onClick={handleCommit}
                disabled={
                  commitStage === "loading" ||
                  loadStage !== "idle" ||
                  !commitMessage.trim() ||
                  !selectedBranch
                }
              >
                {commitStage === "loading" ? (
                  <>
                    <Loader2 className="size-3.5 animate-spin" />
                    Pushing…
                  </>
                ) : (
                  <>
                    <GitCommitHorizontal className="size-3.5" />
                    Push to GitHub
                  </>
                )}
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}
